services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://web-pos-simetri.onrender.com
      - key: APP_KEY
        generateValue: true
